INFO - 2023-06-09 00:01:11 --> Prueba test : object
INFO - 2023-06-09 00:01:11 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 00:01:11 --> Usuario buscado de la BD ----> : John
ERROR - 2023-06-09 00:01:11 --> ErrorException: pg_query(): Query failed: ERROR:  lastval no está definido en esta sesión in D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:152
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\XAMPP\\htdocs...', 152)
#1 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'SELECT LASTVAL(...')
#2 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT LASTVAL(...')
#3 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT LASTVAL(...')
#4 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(445): CodeIgniter\Database\BaseConnection->query('SELECT LASTVAL(...')
#5 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(335): CodeIgniter\Database\Postgre\Connection->insertID()
#6 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#8 D:\XAMPP\htdocs\codeigniter4\app\Controllers\Home.php(32): CodeIgniter\Model->insert(Array, true)
#9 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\XAMPP\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-06-09 00:01:11 --> pg_query(): Query failed: ERROR:  lastval no está definido en esta sesión
in SYSTEMPATH\Database\Postgre\Connection.php on line 152.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  lastval no está definido en esta sesión', 'D:\\XAMPP\\htdocs\\codeigniter4\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 152)
 2 SYSTEMPATH\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'SELECT LASTVAL() AS ins_id')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT LASTVAL() AS ins_id')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT LASTVAL() AS ins_id')
 5 SYSTEMPATH\Database\Postgre\Connection.php(445): CodeIgniter\Database\BaseConnection->query('SELECT LASTVAL() AS ins_id')
 6 SYSTEMPATH\Model.php(335): CodeIgniter\Database\Postgre\Connection->insertID()
 7 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\Home.php(32): CodeIgniter\Model->insert([...], true)
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-06-09 00:37:03 --> Prueba test : object
INFO - 2023-06-09 00:37:03 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 00:37:03 --> Usuario buscado de la BD ----> : John
ERROR - 2023-06-09 00:37:03 --> ErrorException: pg_query(): Query failed: ERROR:  lastval no está definido en esta sesión in D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:152
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\XAMPP\\htdocs...', 152)
#1 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'SELECT LASTVAL(...')
#2 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT LASTVAL(...')
#3 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT LASTVAL(...')
#4 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(445): CodeIgniter\Database\BaseConnection->query('SELECT LASTVAL(...')
#5 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(335): CodeIgniter\Database\Postgre\Connection->insertID()
#6 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#8 D:\XAMPP\htdocs\codeigniter4\app\Controllers\Home.php(31): CodeIgniter\Model->insert(Array, false)
#9 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\XAMPP\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-06-09 00:37:03 --> pg_query(): Query failed: ERROR:  lastval no está definido en esta sesión
in SYSTEMPATH\Database\Postgre\Connection.php on line 152.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  lastval no está definido en esta sesión', 'D:\\XAMPP\\htdocs\\codeigniter4\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 152)
 2 SYSTEMPATH\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'SELECT LASTVAL() AS ins_id')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT LASTVAL() AS ins_id')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT LASTVAL() AS ins_id')
 5 SYSTEMPATH\Database\Postgre\Connection.php(445): CodeIgniter\Database\BaseConnection->query('SELECT LASTVAL() AS ins_id')
 6 SYSTEMPATH\Model.php(335): CodeIgniter\Database\Postgre\Connection->insertID()
 7 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 9 APPPATH\Controllers\Home.php(31): CodeIgniter\Model->insert([...], false)
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-06-09 00:40:39 --> Prueba test : object
INFO - 2023-06-09 00:40:39 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 00:40:39 --> Usuario buscado de la BD ----> : John
INFO - 2023-06-09 00:42:23 --> Prueba test : object
INFO - 2023-06-09 00:42:23 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 00:42:23 --> Usuario buscado de la BD ----> : John
INFO - 2023-06-09 00:43:35 --> Prueba test : object
INFO - 2023-06-09 00:43:35 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 00:43:35 --> Usuario buscado de la BD ----> : John
ERROR - 2023-06-09 00:43:35 --> ErrorException: pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com). in D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:152
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\XAMPP\\htdocs...', 152)
#1 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'INSERT INTO "us...')
#2 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#6 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#8 D:\XAMPP\htdocs\codeigniter4\app\Controllers\Home.php(29): CodeIgniter\Model->insert(Array, false)
#9 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\XAMPP\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-06-09 00:43:35 --> pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com).
in SYSTEMPATH\Database\Postgre\Connection.php on line 152.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com).', 'D:\\XAMPP\\htdocs\\codeigniter4\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 152)
 2 SYSTEMPATH\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "users" ("email", "password", "username") VALUES (:email:, :password:, :username:)', [...], false)
 6 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 9 APPPATH\Controllers\Home.php(29): CodeIgniter\Model->insert([...], false)
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-06-09 01:28:28 --> Prueba test : object
INFO - 2023-06-09 01:28:28 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 01:28:28 --> Usuario buscado de la BD ----> : John
ERROR - 2023-06-09 01:28:28 --> ErrorException: pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com). in D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:152
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\XAMPP\\htdocs...', 152)
#1 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'INSERT INTO "us...')
#2 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#6 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#8 D:\XAMPP\htdocs\codeigniter4\app\Controllers\Home.php(29): CodeIgniter\Model->insert(Array, false)
#9 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\XAMPP\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-06-09 01:28:28 --> pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com).
in SYSTEMPATH\Database\Postgre\Connection.php on line 152.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com).', 'D:\\XAMPP\\htdocs\\codeigniter4\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 152)
 2 SYSTEMPATH\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "users" ("email", "password", "username") VALUES (:email:, :password:, :username:)', [...], false)
 6 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 9 APPPATH\Controllers\Home.php(29): CodeIgniter\Model->insert([...], false)
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-06-09 07:05:38 --> Prueba test : object
INFO - 2023-06-09 07:05:38 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 07:05:38 --> Usuario buscado de la BD ----> : John
INFO - 2023-06-09 07:06:52 --> Prueba test : object
INFO - 2023-06-09 07:06:52 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 07:06:52 --> Usuario buscado de la BD ----> : John
INFO - 2023-06-09 07:22:46 --> Prueba test : object
INFO - 2023-06-09 07:22:46 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 07:22:46 --> Usuario buscado de la BD ----> : John
ERROR - 2023-06-09 07:22:46 --> ErrorException: pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com). in D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:152
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\XAMPP\\htdocs...', 152)
#1 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'INSERT INTO "us...')
#2 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#6 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#8 D:\XAMPP\htdocs\codeigniter4\app\Controllers\Home.php(29): CodeIgniter\Model->insert(Array, false)
#9 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\XAMPP\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-06-09 07:22:46 --> pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com).
in SYSTEMPATH\Database\Postgre\Connection.php on line 152.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com).', 'D:\\XAMPP\\htdocs\\codeigniter4\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 152)
 2 SYSTEMPATH\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "users" ("email", "password", "username") VALUES (:email:, :password:, :username:)', [...], false)
 6 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 9 APPPATH\Controllers\Home.php(29): CodeIgniter\Model->insert([...], false)
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-06-09 07:23:12 --> Prueba test : object
INFO - 2023-06-09 07:23:12 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 07:23:12 --> Usuario buscado de la BD ----> : John
INFO - 2023-06-09 07:25:26 --> Prueba test : object
INFO - 2023-06-09 07:25:26 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 07:25:26 --> Usuario buscado de la BD ----> : John
INFO - 2023-06-09 07:26:04 --> Prueba test : object
INFO - 2023-06-09 07:26:04 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 07:26:04 --> Usuario buscado de la BD ----> : John
ERROR - 2023-06-09 07:26:04 --> ErrorException: pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com). in D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:152
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\XAMPP\\htdocs...', 152)
#1 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'INSERT INTO "us...')
#2 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#6 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#8 D:\XAMPP\htdocs\codeigniter4\app\Controllers\Home.php(29): CodeIgniter\Model->insert(Array, false)
#9 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\XAMPP\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-06-09 07:26:04 --> pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com).
in SYSTEMPATH\Database\Postgre\Connection.php on line 152.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com).', 'D:\\XAMPP\\htdocs\\codeigniter4\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 152)
 2 SYSTEMPATH\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "users" ("email", "password", "username") VALUES (:email:, :password:, :username:)', [...], false)
 6 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 9 APPPATH\Controllers\Home.php(29): CodeIgniter\Model->insert([...], false)
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-06-09 07:48:44 --> Prueba test : object
INFO - 2023-06-09 07:48:44 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 07:48:44 --> Usuario buscado de la BD ----> : John
INFO - 2023-06-09 08:05:52 --> Prueba test : object
INFO - 2023-06-09 08:05:52 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 08:05:52 --> Usuario buscado de la BD ----> : John
INFO - 2023-06-09 08:10:45 --> Prueba test : object
INFO - 2023-06-09 08:10:45 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 08:10:45 --> Usuario buscado de la BD ----> : John
ERROR - 2023-06-09 08:10:45 --> ErrorException: pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com). in D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:152
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\XAMPP\\htdocs...', 152)
#1 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'INSERT INTO "us...')
#2 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#6 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#8 D:\XAMPP\htdocs\codeigniter4\app\Controllers\Home.php(29): CodeIgniter\Model->insert(Array, false)
#9 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\XAMPP\htdocs\codeigniter4\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\XAMPP\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-06-09 08:10:45 --> pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com).
in SYSTEMPATH\Database\Postgre\Connection.php on line 152.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «users_pkey»
DETAIL:  Ya existe la llave (email)=(Robewrto33@hotmail.com).', 'D:\\XAMPP\\htdocs\\codeigniter4\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 152)
 2 SYSTEMPATH\Database\Postgre\Connection.php(152): pg_query(Object(PgSql\Connection), 'INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "users" ("email", "password", "username") VALUES (\'Robewrto33@hotmail.com\', \'15300139\', \'DimitriusPlay\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "users" ("email", "password", "username") VALUES (:email:, :password:, :username:)', [...], false)
 6 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 9 APPPATH\Controllers\Home.php(29): CodeIgniter\Model->insert([...], false)
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-06-09 08:11:04 --> Prueba test : object
INFO - 2023-06-09 08:11:04 --> Prueba test ----> : usuario1@example.com
INFO - 2023-06-09 08:11:04 --> Usuario buscado de la BD ----> : John
